FROM openjdk:13-jdk-slim

ARG version
ARG file_name
ARG dl_URL
ARG ghidra_sha

# VERSION=10.1.2
ENV VERSION=${version}
# ghidra_${VERSION}_PUBLIC_20220125.zip
ENV FILE_NAME={file_name}
# https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_${VERSION}_build/${FILE_NAME}
ENV DL_URL={dl_url}
# ac96fbdde7f754e0eb9ed51db020e77208cdb12cf58c08657a2ab87cb2694940
ENV GHIDRA_SHA={ghidra_sha}

RUN apt-get update && apt-get install -y wget unzip dnsutils --no-install-recommends \
    && wget --progress=bar:force -O /tmp/ghidra.zip ${DL_URL} \
    && echo "$GHIDRA_SHA /tmp/ghidra.zip" | sha256sum -c - \
    && unzip /tmp/ghidra.zip \
    && mv ghidra_${VERSION}_PUBLIC /ghidra \
    && chmod +x /ghidra/ghidraRun \
    && echo "===> Clean up unnecessary files..." \
    && apt-get purge -y --auto-remove wget unzip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /var/cache/apt/archives /tmp/* /var/tmp/* /ghidra/docs /ghidra/Extensions/Eclipse /ghidra/licenses

WORKDIR /ghidra

COPY entrypoint.sh /entrypoint.sh
COPY server.conf /ghidra/server/server.conf

EXPOSE 13100 13101 13102

RUN mkdir /repos

ENTRYPOINT ["/entrypoint.sh"]
CMD ["server"]
